# Generated by Django 5.2.1 on 2025-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequest',
            name='design_stage',
            field=models.CharField(choices=[('Inception', 'Inception'), ('Preliminary Design', 'Preliminary Design'), ('Schematic Design', 'Schematic Design'), ('Design Development', 'Design Development'), ('Tender', 'Tender'), ('Construction Drawing', 'Construction Drawing')], default='Schematic Design', max_length=50),
        ),
    ]
