# Generated by Django 5.2.1 on 2025-05-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskrequest_design_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrequest',
            name='status',
            field=models.CharField(default='Waiting for Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='preferred_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='preferred_team',
            field=models.CharField(blank=True, choices=[('Sustainability', 'Sustainability'), ('BIM', 'BIM'), ('Computational', 'Computational'), ('Building Regs', 'Building Regs'), ('Data Analytics', 'Data Analytics'), ('IT', 'IT'), ('AV', 'AV')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='project_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
