# Generated by Django 5.2.1 on 2025-05-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskrequest_request_date_taskrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='preferred_team',
            field=models.CharField(blank=True, choices=[('Sustainability', 'Sustainability'), ('BIM', 'BIM'), ('Digital Solutions', 'Digital Solutions'), ('Building Regulations', 'Building Regulations'), ('Data Analytics', 'Data Analytics'), ('IT', 'IT'), ('AV', 'AV')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='task_type',
            field=models.CharField(choices=[('Project Research', 'Project Research'), ('Building Analysis', 'Building Analysis'), ('Green Certification', 'Green Certification'), ('BIM', 'BIM'), ('Computational Design', 'Computational Design')], max_length=50),
        ),
    ]
