# Generated by Django 5.2.1 on 2025-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskrequest_preferred_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrequest',
            name='date_requested',
        ),
        migrations.AddField(
            model_name='taskrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='status',
            field=models.CharField(default='Pending Approval', max_length=50),
        ),
    ]
