# Generated by Django 5.2.1 on 2025-06-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskrequest_assigned_team_taskrequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='assigned_team',
            field=models.CharField(blank=True, choices=[('Sustainability', 'Sustainability'), ('BIM', 'BIM'), ('Digital Solutions', 'Digital Solutions'), ('Law', 'Law'), ('Data Analytics', 'Data Analytics'), ('IT', 'IT'), ('AV', 'AV')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='preferred_team',
            field=models.CharField(choices=[('Sustainability', 'Sustainability'), ('BIM', 'BIM'), ('Digital Solutions', 'Digital Solutions'), ('Law', 'Law'), ('Data Analytics', 'Data Analytics'), ('IT', 'IT'), ('AV', 'AV')], default='Sustainability', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
