# Generated by Django 5.2.1 on 2025-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskrequest_assigned_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequest',
            name='collab_team',
            field=models.CharField(blank=True, choices=[('Sustainability', 'Sustainability'), ('BIM', 'BIM'), ('Digital Solutions', 'Digital Solutions'), ('Law', 'Law'), ('Data', 'Data'), ('IT', 'IT'), ('AV', 'AV')], max_length=50, null=True, verbose_name='Collaborating Team'),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='assigned_team',
            field=models.CharField(blank=True, choices=[('Sustainability', 'Sustainability'), ('BIM', 'BIM'), ('Digital Solutions', 'Digital Solutions'), ('Law', 'Law'), ('Data', 'Data'), ('IT', 'IT'), ('AV', 'AV')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='preferred_team',
            field=models.CharField(choices=[('Sustainability', 'Sustainability'), ('BIM', 'BIM'), ('Digital Solutions', 'Digital Solutions'), ('Law', 'Law'), ('Data', 'Data'), ('IT', 'IT'), ('AV', 'AV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskrequest',
            name='task_type',
            field=models.CharField(choices=[('Project Research', 'Project Research'), ('Building Analysis', 'Building Analysis'), ('Green Certification', 'Green Certification'), ('BIM Management', 'BIM Management'), ('BIM Modeling', 'BIM Modeling'), ('Computational Design', 'Computational design'), ('Building Regulations', 'Building Regulations'), ('Data Management', 'Data management')], max_length=50),
        ),
    ]
