# Generated by Django 5.2.1 on 2025-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskrequest_collab_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='task_type',
            field=models.CharField(choices=[('Project Research', 'Project Research'), ('Building Analysis', 'Building Analysis'), ('Green Certification', 'Green Certification'), ('BIM Management', 'BIM Management'), ('BIM Modeling', 'BIM Modeling'), ('Computational Design', 'Computational design'), ('Building Regulations', 'Building Regulations'), ('Data Management', 'Data management'), ('IT Management', 'IT management'), ('AV Management', 'AV management'), ('Other', 'Other')], max_length=50),
        ),
    ]
