# Generated by Django 5.2.1 on 2025-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_department_designstage_iristeam_tasktype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iristeam',
            options={'verbose_name': 'IRIs Team', 'verbose_name_plural': 'IRIs Teams'},
        ),
        migrations.AddField(
            model_name='tasktype',
            name='iris_teams',
            field=models.ManyToManyField(related_name='task_types', to='tasks.iristeam'),
        ),
    ]
