# Generated by Django 4.2.7 on 2025-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_alter_iristeam_options_tasktype_iris_teams"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "DATA – Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="designstage",
            options={
                "verbose_name": "DesignStage",
                "verbose_name_plural": "DATA – DesignStage",
            },
        ),
        migrations.AlterModelOptions(
            name="iristeam",
            options={
                "verbose_name": "IRIs Team",
                "verbose_name_plural": "DATA – IRIs Team",
            },
        ),
        migrations.AlterModelOptions(
            name="taskrequest",
            options={
                "verbose_name": "Task request",
                "verbose_name_plural": "FORM – Task requests",
            },
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={
                "verbose_name": "TaskType",
                "verbose_name_plural": "DATA – TaskType",
            },
        ),
        migrations.AlterField(
            model_name="taskrequest",
            name="attachment",
            field=models.CharField(
                blank=True,
                help_text="Paste a link to shared file or location (e.g., OneDrive, network path)",
                max_length=500,
                null=True,
            ),
        ),
    ]
